### ISSUE TITLE
Working Contract jump marker opens wrong user

### ISSUE THREAD

**Issue by HeinzWuert** [kevinpapst/kimai-plugins#109] opened 2023-10-25 10:23 UTC
As an admin, you can directly select another user from the Working Contract > working times main menu, if no target hours have been defined yet.
If you use the jump marker, the user menu opens, but for your own name and not for the name that is to be edited.

![image](https://github.com/kevinpapst/kimai-plugins/assets/45666972/da72f203-81ad-41f3-97d9-3044a879c11c)

**Comment by kevinpapst** [comment] 2023-10-25 10:44
Nope. The issue is different.
If your own (admin) account is configured as "system user" and therefor invisible in the dropdown, the frontend selects the first entry in the box.
But the page still shows your account data and not the (as in this example) the data for "_Testuser FZ.

That is a weird edge case and I am not sure how to handle that.

**Comment by kevinpapst** [comment] 2024-01-11 20:17
Will be fixed with the next release https://github.com/kimai/kimai/pull/4549 
I added a global solution for that issue, which also occurs on the three report "weekly, monthly, annual by user".

**Comment by kevinpapst** [comment] 2024-01-20 00:24
Fixed with 2.10.0

**Closed by kevinpapst** 2024-01-20 00:24 UTC
Labels: working-times
